### ISSUE TITLE
Implement low-level functions

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/wasm-deploy#1]
Implement functions to
- deploy a single smart contracts with arguments for its constructor and
- execute a transaction for a previously deployed smart contract

## Examples
* Function to deploy a smart contract by name, with constructor arguments
* Example: 
  ```
  deploy(“deployment_name”, {
    from: “<address>”,
    contract: “<contract_name>”,
    args?: [ /*...*/ ],
    log?: (msg: string) => {},
  })
  ```
* Call a deployed contract, passing arguments
* Example: 
  ```
  call(“deployment_name”, {
    from: “<address>”,
    args?: [ /*...*/ ],
    log?: (msg: string) => {},
  })
  ```

**Comment by ashneverdawn** [comment]
I can't seem to assign myself to this one for some reason. But I have started looking into this.

**Comment by TorstenStueber** [comment]
I think that it should work now. Please try again.

**Comment by TorstenStueber** [comment]
Already implemented as part of the other issue and PR. Closed.
