### ISSUE TITLE
Implement fuzz tests

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/wasm-deploy#31]
Nabla now uses fuzz tests (see [here](https://github.com/0xamberhq/curve/blob/acb9abed3810546fa71e77b25efd8e575bd12892/test/NablaCurve.t.sol#L124-L133)), a feature of forge.

Fuzz tests are tests that have a number of arguments. All such arguments need to be of type `bigint`. Fuzz tests are run a number of times (that we can make configurable later) – for now it should be 64 test runs times the number of arguments.

For each test run the test runner should plug in an arbitrary combination of input values for these arguments, each time from the range of uint256 numbers (i.e., 0 to 2**256-1).

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/wasm-deploy/31?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by prayagd** [comment]
@TorstenStueber can you please add estimates to this one?
