### ISSUE TITLE
Implement tests for Nabla indexer

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/wasm-deploy#39]
Implement a new project `nabla-indexer` whose purpose is to test Nabla related code in our Subsquid indexer (see https://github.com/pendulum-chain/pendulum-squids).

For now it is enough if the test run on a locally deployed Foucoco-standalone using a locally deployed indexer.

**Comment by prayagd** [comment]
Moving this to review as i see a PR and reviewers linked
