### ISSUE TITLE
Cannot find module or type declarations for api-solang error

### ISSUE THREAD

**Issue by gianfra-t** [pendulum-chain/wasm-deploy#43]
After installing the packages with `npm i`, attempting to run the project (for example `npx ts-node src/index.ts pull nabla`) shows the following error:

```TSError: ⨯ Unable to compile TypeScript:
src/api/api.ts:22:8 - error TS2307: Cannot find module '@pendulum-chain/api-solang' or its corresponding type declarations.

22 } from "@pendulum-chain/api-solang";
```

Even though the package is properly installed. 

### Workaround
It is possible for the moment to build the package locally, and point to it in the the main `package.json` of the project using `"@polkadot/api-contract": "file:../packages/api-solang"`.

**Comment by prayagd** [comment]
is this blocking something urgent relevant for the ready column priority?

**Comment by gianfra-t** [comment]
I don't think it is blocking since there is a workaround to it, but it is still something that should work.

**Comment by prayagd** [comment]
Iceboxed as not blocking anything
