### ISSUE TITLE
Add code for Nabla prototype deployment

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/wasm-deploy#49]
See https://github.com/pendulum-chain/tasks/issues/346

The code for the deployment is to be added to wasm-deploy.

**Comment by prayagd** [comment]
@TorstenStueber what is the status of this ticket?

**Comment by TorstenStueber** [comment]
@prayagd I just opened [the PR](https://github.com/pendulum-chain/wasm-deploy/pull/50).

**Comment by prayagd** [comment]
Moving to review
