### ISSUE TITLE
Deploy Forex AMM instance for Asset Hub USDC

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/wasm-deploy#53]
With the current version of our runtime we can at most set up 4 swap pools per Nabla instance in production. Unfortunately – with the current version of Nabla – swap pools cannot be removed anymore once they are added to the backstop pool.

The currently used instance for Vortex already has 4 swap pools (USDC.axl, EURC, BRL, ARS) and therefore we can't add Asset Hub USDC to it. Therefore we need to deploy a new instance.

## TODO
* add a new Pendulum deployment declaration to `/nabla/deployments/pendulum`
  * add USDC.axl, Asset Hub USDC, EURC.Circle, ARS swap pools
  * keep other parameters mostly as in `/nabla/deployments/pendulum/usdcAxelarVortexPrototype.ts`
    * this deployment is also described [on Notion](https://www.notion.so/satoshipay/24-07-04-USDC-axl-Prototype-Deployment-1118b1b29b2f80c7ba3ad321c6bb3e8b)
* execute the deployment using wasm-deploy
* add a description [to Notion](https://www.notion.so/satoshipay/24-05-16-Nabla-Pendulum-Deployment-c7cefd58f44c428a92ceaea30c603286)
* open a new draft PR in the Portal repository similar [to this one](https://github.com/pendulum-chain/portal/pull/519) that would allow to interact with the new instance using the preview deployment
* use USDC (AH) for the backstop pool currency

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/wasm-deploy/53?planning-poker) with Zenhub @ebma @gianfra-t @Sharqiewicz

**Comment by ebma** [comment]
@pendulum-chain/product can you clarify the question about the backstop pool asset?

**Comment by prayagd** [comment]
I vote for USDC

**Comment by TorstenStueber** [comment]
This instance is described [on Notion](https://www.notion.so/satoshipay/24-11-14-USDC-Asset-Hub-Prototype-Deployment-13e8b1b29b2f801a874ae384dd36c4a6).

This instance can be accessed via [a preview deployment](https://deploy-preview-619--rococo-souffle-a625f5.netlify.app/pendulum/nabla/swap-pools).
